CREATE DATABASE IF NOT EXISTS daspacer;

USE daspacer;

CREATE TABLE IF NOT EXISTS user_choices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    choice ENUM('DA', 'SPACER') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
